- authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
- authentication/src/main/java/com/learnandphish/authentication/JwtUserDetailsService.java
- authentication/src/test/java/com/learnandphish/authentication/JwtUserDetailsServiceTest.java
This PR fixes #7 
It brings a differenciation between the errors that can arise when calling the authentication endpoint.
It also brings testing to the JwtUserDetailsService class
This has been tested using the new unit testing class JwtUserDetailsServiceTest
> #7 Improved error handling and testing

- .gitignore
- authentication/src/main/java/com/learnandphish/authentication/UserData.java
- databases/scripts/authentication_init.sql
- docker-compose.yml
- moved authentication_db to databases directory
- enabled auto db init
- added .gitignore
> docker-compose database improvements

- authentication/Dockerfile
- authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
- authentication/src/main/java/com/learnandphish/authentication/JWTUtil.java
- authentication/src/main/java/com/learnandphish/authentication/PublicKeyController.java
- gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
- gateway/src/main/java/com/learnandphish/gateway/JWTUtil.java
Fixes #14 by keeping the previous key when the authentication service restarts
> #14 keep previous key when authentication service restarts

- authentication/build.gradle
- authentication/src/main/java/com/learnandphish/authentication/WebSecurityConfig.java
- authentication/src/main/resources/application.yaml
- docker-compose.yml
- gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
Implemented swagger-ui
Restricted port 8082 to prevent outside access (fixes #16 )
> Swagger UI

- authentication/src/main/java/com/learnandphish/authentication/JWTUtil.java
- gateway/build.gradle
- gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
- gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
- gateway/src/main/java/com/learnandphish/gateway/RouteRoles.java
Included the user role to jwt claims
> Added roles to jwt

- authentication/src/main/java/com/learnandphish/authentication/AuthenticationApplication.java
- authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
- authentication/src/main/java/com/learnandphish/authentication/UserData.java
- authentication/src/main/java/com/learnandphish/authentication/UserExportService.java
- authentication/src/main/java/com/learnandphish/authentication/WebSecurityConfig.java
- databases/scripts/authentication_init.sql
- gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
Now able to dowload user list as csv.
Only admin role should be able to access it, which is not the case now
> get user list in csv

- README.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
chore
> chore: change project name in README

- frontend/src/app.css
- frontend/tailwind.config.ts
> feat: create custom theme.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/components/custom/Separator.svelte
- frontend/src/routes/password/+page.svelte
- frontend/src/types/zxcvbn.d.ts
> Feat(frontend): add password tester.

- authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
- authentication/src/main/java/com/learnandphish/authentication/EmailSender.java
> refactor: change emailContent to html

- authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
- authentication/src/main/java/com/learnandphish/authentication/user/GophishUserDTO.java
- authentication/src/main/java/com/learnandphish/authentication/user/GophishUserDataRepository.java
- authentication/src/main/java/com/learnandphish/authentication/user/UserExportService.java
- docker-compose.yml
- gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
- gateway/src/main/java/com/learnandphish/gateway/RouteRoles.java
- gateway/src/main/resources/application.properties
- gateway/src/main/resources/application.yaml
- Added userlist for gophish group creation
- Cleaned up docker compose & application properties
- Fixed authenticaion-service startup before its db
> Gophish Userlist

- authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
- gateway/src/main/java/com/learnandphish/gateway/RouteRoles.java
- gateway/src/main/resources/application.properties
THIS IS A HOTFIX FOR BASTIEN (sry Maxime)
> feat: add need password change check

- docker-compose.yml
- formation/src/main/resources/application.properties
- Fixes formation db driver issue
- Adds pulling spiderfoot repo for image build
> fix: pull and build spiderfoot from repo

- frontend/src/lib/components/custom/header.svelte
- frontend/src/lib/services/AuthService.ts
- frontend/src/routes/(app)/+layout.server.ts
- frontend/src/routes/(app)/+layout.svelte
- frontend/src/routes/change-password/+page.server.ts
- frontend/src/routes/change-password/change-password-form.svelte
- frontend/src/routes/change-password/schema.ts
- frontend/src/routes/login/+page.server.ts
- frontend/src/routes/login/+page.svelte
- frontend/src/routes/login/login-form.svelte
Check if user need to change password
Fixes # 58
> 58 check password change

- frontend/src/lib/components/custom/ConnectionCard.svelte
- frontend/src/lib/components/magicUi/Particles.svelte
- frontend/src/lib/services/AuthService.ts
- frontend/src/routes/login/+page.server.ts
- frontend/src/routes/login/+page.svelte
- frontend/src/routes/login/login-form.svelte
Fix multiples issues from login page.
Fixes #64 
> 64 login issues

- frontend/src/lib/components/custom/header.svelte
- frontend/src/lib/services/AuthService.ts
- frontend/src/routes/(app)/+layout.svelte
- frontend/src/routes/api/auth/get-user/+server.ts
> 74 get user info

- frontend/package-lock.json
- frontend/package.json
Update multiple packages
Fixes #81 
> 81 packages updates

- frontend/src/routes/login/+page.server.ts
Prevent useless api call and recreation of validation schema each time
Fixes # (issue)
> fix login page

- frontend/package-lock.json
- frontend/src/lib/components/custom/Sidebar.svelte
- frontend/src/lib/components/custom/TapBar.svelte
- frontend/src/lib/components/custom/phishing/EditPage.svelte
- frontend/src/lib/components/custom/phishing/EditTemplate.svelte
- frontend/src/lib/components/custom/phishing/NewCampaign.svelte
- frontend/src/lib/components/custom/phishing/NewPage.svelte
- frontend/src/lib/components/custom/phishing/NewTemplate.svelte
- frontend/src/lib/components/custom/phishing/TemplatePopup.svelte
- frontend/src/lib/components/ui/aspect-ratio/aspect-ratio.svelte
- frontend/src/lib/components/ui/aspect-ratio/index.ts
- frontend/src/routes/(app)/+layout.svelte
- frontend/src/routes/(app)/formation/+page.svelte
- frontend/src/routes/(app)/osint/+page.svelte
- frontend/src/routes/(app)/password/+page.svelte
- frontend/src/routes/(app)/phishing/+page.svelte
- frontend/src/routes/(app)/phishing/addgroup/+page.svelte
- frontend/src/routes/(app)/phishing/campaigns/+page.svelte
- frontend/src/routes/(app)/phishing/campaigns/[id]/+page.svelte
- frontend/src/routes/(app)/phishing/editgroup/[id]/+page.svelte
- frontend/src/routes/(app)/phishing/email-templates/+page.svelte
- frontend/src/routes/(app)/phishing/page-templates/+page.svelte
> 89 responsive

- frontend/src/routes/(app)/phishing/addgroup/+page.svelte
- frontend/src/routes/(app)/phishing/editgroup/[id]/+page.svelte
> Fix: edit gophish group calls
